package BitMagic;
//to find the maximum AND value generated by any pair of elements in the array.
public class maxAndValue {
    public static void main(String[] args) {
        int[] arr = {4, 8, 12, 16};
        System.out.println(answer(arr));
    }
    //naive
    //tc is o(N*N)
    static int answer(int[] arr){
        int ans = 0;
        for(int i = 0 ; i < arr.length - 1 ; i++){
            for(int j = i + 1 ; j < arr.length ; j++){
                ans = Math.max(ans, arr[i]&arr[j]);
            }
        }
        return ans;
    }

    //efficient method
    //
    static int answer1(int[] arr){
        return -1;
    }
}
